engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      max-statements:
        enabled: false
      complexity:
        enabled: false
# ... CONFIG CONTENT ...